name: test
on:
  - push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - run: |
          cat  ${{github.event_path}}
          echo ${{github.event.repository.html_url}}
