name: test
on:
  - push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - run: |
          echo ${{github.event_path}}
      - name: Upload all
        uses: actions/upload-artifact@v2
        with:
          path: ${{github.event_path}}
