name: test
on:
  - push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - run: |
          julia --project -e 'using Pkg; Pkg.add(PackageSpec(url = "https://github.com/aminya/GitHubActions.jl", rev = "test")); using GitHubActions; println(EVENT)'
